### ISSUE TITLE
Consent checkbox to meet GDPR

### ISSUE THREAD

**Issue by rubengc** [groundhoggwp/holler-box#18]
Hi!

For GDPR is required to add a specific consent checkbox that user is required to check when provides personal data (name, email, address, etc)

For Mailchimp integration, is mandatory to add a required checkbox with a message like "I consent the collection of my email that will be added to your newsletter"

Hope you can add it as soon as posible because (as for sure you know) GDPR comes the 25th of this month 😨

**Comment by scottopolis** [comment]
Hi, this is not my understanding of GDPR.  GDPR requires the user to take action when giving up personal information, and if they add their email to an opt-in and press "submit" that counts. I don't think this is any violation of GDPR. If you have specific documentation saying otherwise, please link to it here.

**Comment by tobeyadr** [comment]
Hi Ruben, HollerBox 2.0 will remedy this
